### ISSUE TITLE
The Search Fail Sometimes

### ISSUE THREAD

**Issue by pelegkaz** [Tashbezaleh/Tashbezaleh#12]
Sometimes, The search tries downloading big files or sites, and failed.

**Comment by teldkeng** [comment]
It seems like there may by a problem with encoding (again).
a link to the program's LOGs

https://console.developers.google.com/project/tashbezale/logs?service=appengine.googleapis.com&key1=default&key2=1&logName=appengine.googleapis.com%2Frequest_log&minLogLevel=0&expandAll=false&timezone=Europe%2FBucharest

**Comment by pelegkaz** [comment]
I had a problem while downloading big files. (urllib error about waiting too long)

**Comment by yehonatanz** [comment]
That's mostly solved, please list here any specific bugs you encounter and how to reproduce them.
@Tashbezaleh @pelegkaz @teldkeng @megalm1
