### ISSUE TITLE
Reset DB

### ISSUE THREAD

**Issue by pelegkaz** [Tashbezaleh/Tashbezaleh#13]
The way we use to reset the db doesn't work for ndb in google app engine due to quota.
Must find other way, or slice it into 10 days.

**Comment by teldkeng** [comment]
Some data gathered:
- the program stored less than 10 MB in total:
  https://console.developers.google.com/project/tashbezale/datastore/stats
- however, from the logs it seems like it tried to write a lot more:
  https://console.developers.google.com/project/tashbezale/logs?service=appengine.googleapis.com&key1=default&key2=1&logName=appengine.googleapis.com%2Frequest_log&minLogLevel=0&expandAll=false&timezone=Europe%2FBucharest&filters=text:reset&lastVisibleOffset=555b3bc600ff0c6cecad276f670001737e7461736862657a616c65000131000100&lastVisibleTimestampNanos=1432042496705000000

Moreover, locally it stores also less than 10 MB.
technical data:
-  Scanned 16006 entities of total 4331538 bytes, 144263 index entries of total 8832089 bytes and 15982 composite index entries of total 4448484 bytes. Inserted 25 new records.

another deployment with a partial-db reset was initiated

**Comment by teldkeng** [comment]
A very very small deployment, the first 853 lines of the file, about 1/16 even according to the size loccally.

I am not sure but, it seems that it works, return 200, even though the log suggest that there was an error because it still exceeds the size. very weird because locally it takes much less space....

**Comment by teldkeng** [comment]
More data: after another attempt to reset the db it fails already in the cleaning, meaning before the regular writes to the db

**Comment by pelegkaz** [comment]
Tal need to check that the reset, initialize work. (and to deploy a version which actually work)
meaning, make a working actual final online database

**Comment by teldkeng** [comment]
From some more study, it seems that cleaning the db also takes a lot of write ops, and therefore should also be performed in parts.
https://cloud.google.com/appengine/pricing (in cost of datastore calls)

i will fix it.

**Comment by teldkeng** [comment]
solved.
