### ISSUE TITLE
Help Pages

### ISSUE THREAD

**Issue by pelegkaz** [Tashbezaleh/Tashbezaleh#15]
We need to make help pages to explain how to use the system.

**Comment by pelegkaz** [comment]
Made. Need to make help for add definition

**Comment by Tashbezaleh** [comment]
Tel needs to write a page for milestone 3 with instructions

**Comment by Tashbezaleh** [comment]
Updating those of the minigames (new hints, Gal-Is-Awesome), pattern in index page (Gal-Is-Awesome)
making new for: Forums, Contact us

**Comment by pelegkaz** [comment]
Updating other also since design changes.
