### ISSUE TITLE
Source of db equals Source of online search

### ISSUE THREAD

**Issue by Tashbezaleh** [Tashbezaleh/Tashbezaleh#17]
[From milestone 2 meeting]
change the source of an answer that is represented for an answer that it's source is the db or the algorithm to a single source.

**Comment by pelegkaz** [comment]
It doesn't solve the case. Don't we want to still save it differently in the db but just view it the same?

**Comment by pelegkaz** [comment]
And are we going to reset the db, or just add it the rest of the entities?
If we are not going to reset the db, this solution won't work.

**Comment by pelegkaz** [comment]
Will be saved the same in the db. The current db will be erased before the new deployment.
