### ISSUE TITLE
Feature 0: Definition Search

### ISSUE THREAD

**Issue by Tashbezaleh** [Tashbezaleh/Tashbezaleh#2]
_Feature Name:_ Definition Search

_Description:_ Every user can type a definition and its regex, and will get the answer.

_Requires:_ understanding how to automatically search google. storing databse, and searching in it.

_Due:_ Milestone 2 (BETA)

_Status:_ Html close to finish, python algorithm not.

**Comment by teldkeng** [comment]
[From milestone 2 meeting]
add a spinner while the server is computing his answer after the user has clicked search. The goal is to indicate to the user that his request has been received and the answer is on the way.

**Comment by teldkeng** [comment]
[From milestone 2 meeting]

**Comment by teldkeng** [comment]
[From milestone 2 meeting]
change the source of an answer that is represented for an answer that it's source is the db or the algorithm to a single source.

**Comment by teldkeng** [comment]
[From milestone 2 meeting]
when showing answer, let answer come gradually such that when one is found it will be shown.
