### ISSUE TITLE
Button: "Know The Answer?"

### ISSUE THREAD

**Issue by Tashbezaleh** [Tashbezaleh/Tashbezaleh#21]
In the bottom of the results, button of "Know The Answer?" which will lead to add definition.

**Comment by pelegkaz** [comment]
Button Added. I need to make a design for it..

**Comment by pelegkaz** [comment]
Gal needs to verify whether it is fine : :smile: 
what does document.ready in results affect. @megalm1

**Comment by pelegkaz** [comment]
Answer: doesn't do anything, therefore removed.
Design is still missing.
