### ISSUE TITLE
Site Icon in live version doen't work

### ISSUE THREAD

**Issue by teldkeng** [Tashbezaleh/Tashbezaleh#33]
probably has something to do with app.yaml and static files upload

**Comment by pelegkaz** [comment]
Do you talk about the four black-white squares? I can see them in tashbezale.appengine.com

**Comment by teldkeng** [comment]
Yes i talk about that. it still doesn't work on my pc:
![image](https://cloud.githubusercontent.com/assets/6844576/8026358/d44693d8-0d7a-11e5-8013-4b223b5d3009.png)

However, maybe the live version that is running now is a bit old.

we should check it later on.

**Comment by teldkeng** [comment]
I tried refreshing multiple times, it didn't work. I clicked "reload"  on the tab and it worked.
The problem probably had something to do with the browser caching of the old version's icon.
