### ISSUE TITLE
Feature 3: Clues

### ISSUE THREAD

**Issue by Tashbezaleh** [Tashbezaleh/Tashbezaleh#5]
Feature Name: Clues

Description: If a solution is surely right, the user can ask for a clue (some of the letters).

Requires: html page, python algorithm for clues, and for being sure about a definition, server side.

Due: 3.6

Status: Nothing

Time Estimation: 12 hours

**Comment by pelegkaz** [comment]
Gal: Front hand, Yoni: Back hand
