### ISSUE TITLE
Documentation of the code

### ISSUE THREAD

**Issue by Tashbezaleh** [Tashbezaleh/Tashbezaleh#77]
We aren't sure if adding comments in the code is enough. Should check this.

**Comment by yehonatanz** [comment]
"link to the final project documentation (architectural overview, main APIs, installation and usage instructions)", from https://sites.google.com/site/cloudweb14b/final-submission

**Comment by pelegkaz** [comment]
scoringBoardUtils, minigamesUtils are the only files left. (beside architectural overview and main APIs)

**Comment by pelegkaz** [comment]
https://github.com/Tashbezaleh/Tashbezaleh/wiki/Project-Documentation
